//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace ReSharperPlugin.RdProtocol
{
  
  
  /// <summary>
  /// <p>Generated from: Model.kt:10</p>
  /// </summary>
  public class RemodderProtocolModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<string[], string[]> Decompile => _Decompile;
    
    //private fields
    [NotNull] private readonly RdCall<string[], string[]> _Decompile;
    
    //primary constructor
    private RemodderProtocolModel(
      [NotNull] RdCall<string[], string[]> decompile
    )
    {
      if (decompile == null) throw new ArgumentNullException("decompile");
      
      _Decompile = decompile;
      _Decompile.Async = true;
      BindableChildren.Add(new KeyValuePair<string, object>("decompile", _Decompile));
    }
    //secondary constructor
    internal RemodderProtocolModel (
    ) : this (
      new RdCall<string[], string[]>(ReadStringArray, WriteStringArray, ReadStringArray, WriteStringArray)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<string[]> ReadStringArray = JetBrains.Rd.Impl.Serializers.ReadString.Array();
    
    public static  CtxWriteDelegate<string[]> WriteStringArray = JetBrains.Rd.Impl.Serializers.WriteString.Array();
    
    protected override long SerializationHash => 2555462534816406283L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(JetBrains.Rider.Model.IdeRoot), JetBrains.Rider.Model.IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("RemodderProtocolModel (");
      using (printer.IndentCookie()) {
        printer.Print("decompile = "); _Decompile.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionRemodderProtocolModelEx
   {
    public static RemodderProtocolModel GetRemodderProtocolModel(this JetBrains.Rider.Model.Solution solution)
    {
      return solution.GetOrCreateExtension("remodderProtocolModel", () => new RemodderProtocolModel());
    }
  }
}
