name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: configure_java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
      - run: ./gradlew :buildPlugin --no-daemon
      - run: ./gradlew :buildResharperPlugin --no-daemon
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ github.event.repository.name }}.CI.${{ github.head_ref || github.ref_name }}
          path: output
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: configure_java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew :testDotNet --no-daemon