name: Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: configure_java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish Rider Package
        run: ./gradlew :publishPlugin -PBuildConfiguration="Release" -PPluginVersion="${{ github.ref_name }}" -PPublishToken="${{ secrets.PUBLISH_TOKEN }}"
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - run: ./gradlew :buildResharperPlugin
      - name: Publish ReSharper Package
        run: dotnet nuget push --source "https://plugins.jetbrains.com/api/v2/package" --api-key "$PUBLISH_TOKEN" output/ReSharperPlugin*.nupkg
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Upload binaries to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} output/*