name: Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Publish:
    runs-on: windows-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: configure_java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew :publishPlugin -PBuildConfiguration="Release" -PPluginVersion="${{ github.ref_name }}" -PPublishToken="${{ secrets.PUBLISH_TOKEN }}"
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Upload binaries to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} output/*